language: ruby
cache: bundler
sudo: enabled
before_install:
- "./.travis/install_deps.sh"
- gem update --system
- gem install bundler
stages:
- name: test
jobs:
  include:
  - stage: test
    rvm: 2.5.1
    name: test osx
    script: "./.travis/test.sh"
    os: osx
  - stage: test
    name: test linux
    rvm: 2.5.1
    script: "./.travis/test.sh"
    os: linux
    dist: xenial
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: rubyc-*gz
  on:
    tags: true
  api_key:
    secure: n9Dch4VD7OHnAzNEji7BqCf6Ihv+RwHQGwhTacbuOG2hX6CWRfKOey6/N/RDIs1Bw0tkNWtAzb/NaNMjNeJwGDCsj7I/Bs8jlNIWyiNRp88cYFJcb2QTKfuMWpT1KRHXq/3XEyAhRUQ7LcGiQXxfwBwYKOKMIyZt2PooTr0D6fY/ThjvJmYePo5j4xP8F8Fst+ic0ASJkHVwDqrf5O+JkiXepmaOl8Y4AkOdK2Vhk2tvwFXZmNom6+ieM2z9KwzuaqUrCHFyd7OuLDHUGMjF96yy9vgk/lP/1mSkNneO/rCm8LmYWsNWul+M0hEBWrFshVFkhoHgU9I+zwn9x4wrJYEB2aRfTq0DNyqwvDWKNBlhP+VgpMXEHbyRGPtd9H4MHenpN6jm+3V2tEU3K0i2u5/vGtx11eg8pNcxWYgPjvmnZtYleOgFdu1SmkKZOCQffFemMJh/vEppPWknIEZBFK4GzFaEoPA3utXlQh20I37sRk3N/BQKUY5U7mEtc6lH4+LkeRl3H2UEM0fmo8LyE3fgKC5P1zVyXyI0IGlcMIXojr77RAnvjw4Ttjw+wrjRArAuw+QZfXCc+76qLiIykb+bRaJU0tLcMXfC0FAvZIE2uxOuFJ3xA6rynuP6MaGWhASalRvVd64mb1MmW6g7Km5My67196BzUPP2YutQM88=
